# Generated by Django 4.0.1 on 2022-02-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gamer', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
    ]
