# Generated by Django 4.0.1 on 2022-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catches',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('buyer_id', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=20)),
                ('fisher_id', models.CharField(max_length=8)),
                ('date', models.DateTimeField()),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
