# Generated by Django 4.0.1 on 2022-02-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FishRevenue', models.IntegerField()),
                ('FishCost', models.IntegerField()),
                ('FishProfit', models.IntegerField()),
                ('SupplyRevenue', models.IntegerField()),
                ('SupplyCost', models.IntegerField()),
                ('SupplyProfit', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
