# Generated by Django 4.0.1 on 2022-02-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catches',
            name='date',
            field=models.DateField(),
        ),
    ]
